### ISSUE TITLE
Incorrect "part of core perl install" detection

### ISSUE THREAD

**Issue by bldewolf** [gentoo-perl/g-cpan#17]
When generating an ebuild for the Iterator module, g-cpan incorrectly determines that it's part of the core perl install:

    $ g-cpan -g Iterator
     * Iterator is part of the core perl install

This is because TAP::Parser::Iterator is part of perl core and the code for determining core membership only cares about the basename of the package and not the full path.  After editing g-cpan to skip this check, the ebuild generates fine.

**Comment by bor** [comment]
I'll try to handle such issue if nobody mind.

**Comment by bor** [comment]
##### List of affected modules

Module | In core | In portage | Status for 0.16.6 | Status for proposed PR
--------- | --- | --- | --- | ---
CPAN   | Yes | Yes | ok  | ?
JSON   | Yes | Yes | fail | ?
Iterator | Yes | No  | fail | ?

Please provide more examples if you have.
