### ISSUE TITLE
Fails on packages there is mismatching between module & package versions

### ISSUE THREAD

**Issue by jmfernandez** [gentoo-perl/g-cpan#23]
Meanwhile I was trying to generate an ebuild for OWL::Simple::Parser module, the digestion phase failed because g-cpan used as version number the one from the module (1.01) instead of the one from the whole Perl package (0.51) which contains it, as you can see at http://cpansearch.perl.org/src/TOMASZ/OWL-Simple-0.51/META.json

So, all these commands generate wrong ebuilds:

* `g-cpan -g OWL::Simple::Parser` -> FAILS (misuses version 1.01 instead of 0.51)
* `g-cpan -g OWL::Simple::OBOWriter` -> FAILS (misuses version 0.06 instead of 0.51)
* `g-cpan -g OWL-Simple` -> FAILS (due the package does not contain a OWL::Simple module)

I tested this with g-cpan 0.16.6 and master version, with the same results.

**Comment by jmfernandez** [comment]
I have also realized that the generated ebuild contains a wrong dependency on dev-lang/io

**Comment by bor** [comment]
Also https://bugs.gentoo.org/show_bug.cgi?id=542180

**Comment by bor** [comment]
@jmfernandez please test current live version,
is it ok for you now?
`emerge =app-portage/g-cpan-9999`

**Comment by jmfernandez** [comment]
The first two cases now work as expected (nice!):

* `g-cpan -g OWL::Simple::Parser`
* `g-cpan -g OWL::Simple::OBOWriter`

but the third one still fails:

* `g-cpan -g OWL-Simple` -> FAILS (due the package does not contain a OWL::Simple module)

Perhaps this last one should be treated in a different issue.

**Comment by jmfernandez** [comment]
```
# g-cpan -g OWL-Simple
-CPAN::SQLite not installed, trying to work without
Reading '/root/.cpan/Metadata'
  Database was generated on Sun, 22 May 2016 23:29:02 GMT
 * OWL::Simple is not a CPAN module!
Use of uninitialized value in lc at /usr/bin/g-cpan line 605.
Use of uninitialized value in lc at /usr/bin/g-cpan line 609.
```

**Comment by bor** [comment]
Good.
Indeed, this is enhancement about to support package names as well as module names.
I will create issue about this. And once it will be handled ;)
