### ISSUE TITLE
update list of 'converted packages names'  (gentoo #578678)

### ISSUE THREAD

**Issue by bor** [gentoo-perl/g-cpan#28]
Were was a huge move(rename) for perl packages in 1Q-2016, to use proper names.
And this is a good update :)
But we need to keep a list of 'non-proper' names up-to-date, in g-cpan (Gentoo::Portage).

https://bugs.gentoo.org/show_bug.cgi?id=578678

**Comment by kentfredric** [comment]
Its kinda worth noting I track some of the ones I'm aware of with this: https://metacpan.org/release/Gentoo-Util-VirtualDepend 

https://metacpan.org/source/KENTNL/Gentoo-Util-VirtualDepend-0.003013/maint/update-dist-to-gentoo.pl#L144

I've probably missed some, but that's what I have, and its rapidly dwindling.

**Comment by bor** [comment]
Thanks @kentfredric !
I've already found it by few shell commands (thanks `ack`)
But I will review your list also, it might helps also.

**Comment by bor** [comment]
@kentfredric I've reviewed your module. Good work!
Seems like a easiest way to handle such issues in the future is moving to use your module ;)

**Comment by kentfredric** [comment]
:)

**Comment by kentfredric** [comment]
Probably worth mentioning I have a few virtuals described in that data that don't exist in ::gentoo, but I argue "we should probably do this one day", ( and they're in the overlay ).

I should probably fence those out till it actually happens.
