### ISSUE TITLE
[Feature Request] EAPI 7 support

### ISSUE THREAD

**Issue by leycec** [gentoo-perl/g-cpan#45]
`g-cpan` currently generates EAPI 5-compliant ebuilds. That's not necessarily the worst thing that's ever happened. Still, it would be *strongly* preferable if `g-cpan` generated EAPI 7-compliant ebuilds instead. EAPI 5 is over six years old and increasingly unsupported across various eclasses – thankfully excluding the `perl-module` eclass, of course!

Thanks as always for all the CPAN automation, fearless `g-cpan` crew.

**Comment by ulm** [comment]
Just a heads-up: The number of EAPI 5 ebuilds in the Gentoo repository is down to 9, so EAPI 5 will be banned soon. Eclasses can be expected to be cleaned up afterwards. This will include `eutils.eclass` which is inherited by `perl-module.eclass`, so things will break at that point.

I'd suggest to skip EAPI 7 and update to EAPI 8 immediately.

**Comment by joakim-tjernlund** [comment]
EAPI=5 is banned now

**Comment by ostroffjh** [comment]
And this is causing emerge to complain loudly for any perl package created by g-cpan.  A patch was just submitted as a PR this morning. (See bug 819513)

**Comment by thesamesam** [comment]
Done with 83bac731ac560c9261cfb523853e6d9b8fab9888 (https://github.com/gentoo-perl/g-cpan/pull/50) and fixed in 0.18.0, which was just tagged & pushed to gentoo.
